# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Multi_Modules_Interface(object):
    def setupUi(self, Multi_Modules_Interface):
        Multi_Modules_Interface.setObjectName("Multi_Modules_Interface")
        Multi_Modules_Interface.resize(1053, 848)
        Multi_Modules_Interface.setMinimumSize(QtCore.QSize(1053, 848))
        self.centralwidget = QtWidgets.QWidget(Multi_Modules_Interface)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 190, 91, 31))
        self.label.setMinimumSize(QtCore.QSize(91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 470, 61, 17))
        self.label_2.setMinimumSize(QtCore.QSize(61, 17))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 30, 81, 31))
        self.label_4.setMinimumSize(QtCore.QSize(51, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 190, 81, 31))
        self.label_5.setMinimumSize(QtCore.QSize(81, 31))
        self.label_5.setMaximumSize(QtCore.QSize(81, 31))
        self.label_5.setObjectName("label_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(30, 30, 981, 111))
        self.tableWidget_2.setMinimumSize(QtCore.QSize(941, 61))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.lineEdit_Parametrs = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Parametrs.setGeometry(QtCore.QRect(160, 100, 811, 25))
        self.lineEdit_Parametrs.setMinimumSize(QtCore.QSize(311, 25))
        self.lineEdit_Parametrs.setObjectName("lineEdit_Parametrs")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 30, 51, 31))
        self.label_6.setMinimumSize(QtCore.QSize(51, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(480, 0, 51, 31))
        self.label_7.setMinimumSize(QtCore.QSize(51, 31))
        self.label_7.setObjectName("label_7")
        self.textEdit_Console = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Console.setGeometry(QtCore.QRect(30, 500, 981, 241))
        self.textEdit_Console.setObjectName("textEdit_Console")
        self.textEdit_Modules = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Modules.setGeometry(QtCore.QRect(420, 230, 591, 211))
        self.textEdit_Modules.setObjectName("textEdit_Modules")
        self.textEdit_Directs = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Directs.setGeometry(QtCore.QRect(30, 230, 371, 211))
        self.textEdit_Directs.setObjectName("textEdit_Directs")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(580, 440, 271, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Start_modules_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.Start_modules_Button.setMinimumSize(QtCore.QSize(89, 25))
        self.Start_modules_Button.setObjectName("Start_modules_Button")
        self.horizontalLayout_3.addWidget(self.Start_modules_Button)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(640, 150, 160, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Start_module_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Start_module_Button.setMinimumSize(QtCore.QSize(151, 25))
        self.Start_module_Button.setObjectName("Start_module_Button")
        self.verticalLayout_2.addWidget(self.Start_module_Button)
        self.AddModule_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.AddModule_Button.setMinimumSize(QtCore.QSize(101, 25))
        self.AddModule_Button.setObjectName("AddModule_Button")
        self.verticalLayout_2.addWidget(self.AddModule_Button)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 60, 691, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_directs = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_directs.setMinimumSize(QtCore.QSize(211, 25))
        self.comboBox_directs.setObjectName("comboBox_directs")
        self.horizontalLayout.addWidget(self.comboBox_directs)
        self.comboBox_modules = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_modules.setMinimumSize(QtCore.QSize(201, 25))
        self.comboBox_modules.setObjectName("comboBox_modules")
        self.horizontalLayout.addWidget(self.comboBox_modules)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(800, 60, 171, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Info = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Info.setMinimumSize(QtCore.QSize(89, 25))
        self.pushButton_Info.setObjectName("pushButton_Info")
        self.horizontalLayout_2.addWidget(self.pushButton_Info)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(70, 90, 93, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_8.setMinimumSize(QtCore.QSize(91, 31))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.Clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Clear_Button.setGeometry(QtCore.QRect(670, 750, 269, 25))
        self.Clear_Button.setMinimumSize(QtCore.QSize(89, 25))
        self.Clear_Button.setObjectName("Clear_Button")
        self.label.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.tableWidget_2.raise_()
        self.lineEdit_Parametrs.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.textEdit_Console.raise_()
        self.label_4.raise_()
        self.textEdit_Modules.raise_()
        self.textEdit_Directs.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.verticalLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.Clear_Button.raise_()
        Multi_Modules_Interface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Multi_Modules_Interface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1053, 22))
        self.menubar.setObjectName("menubar")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        Multi_Modules_Interface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Multi_Modules_Interface)
        self.statusbar.setObjectName("statusbar")
        Multi_Modules_Interface.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(Multi_Modules_Interface)
        self.actionSave.setObjectName("actionSave")
        self.actionReload = QtWidgets.QAction(Multi_Modules_Interface)
        self.actionReload.setObjectName("actionReload")
        self.actionCreate = QtWidgets.QAction(Multi_Modules_Interface)
        self.actionCreate.setObjectName("actionCreate")
        self.actionLoad = QtWidgets.QAction(Multi_Modules_Interface)
        self.actionLoad.setObjectName("actionLoad")
        self.actionClear_all = QtWidgets.QAction(Multi_Modules_Interface)
        self.actionClear_all.setObjectName("actionClear_all")
        self.menuSave.addAction(self.actionCreate)
        self.menuSave.addAction(self.actionLoad)
        self.menuSave.addAction(self.actionSave)
        self.menuSave.addAction(self.actionReload)
        self.menuSave.addAction(self.actionClear_all)
        self.menubar.addAction(self.menuSave.menuAction())

        self.retranslateUi(Multi_Modules_Interface)
        QtCore.QMetaObject.connectSlotsByName(Multi_Modules_Interface)

    def retranslateUi(self, Multi_Modules_Interface):
        _translate = QtCore.QCoreApplication.translate
        Multi_Modules_Interface.setWindowTitle(_translate("Multi_Modules_Interface", "MainWindow"))
        self.label.setText(_translate("Multi_Modules_Interface", "Using Directs"))
        self.label_2.setText(_translate("Multi_Modules_Interface", "Console"))
        self.label_4.setText(_translate("Multi_Modules_Interface", "Programm"))
        self.label_5.setText(_translate("Multi_Modules_Interface", "Modules"))
        self.label_6.setText(_translate("Multi_Modules_Interface", "Direct"))
        self.label_7.setText(_translate("Multi_Modules_Interface", "Module"))
        self.Start_modules_Button.setText(_translate("Multi_Modules_Interface", "Start "))
        self.Start_module_Button.setText(_translate("Multi_Modules_Interface", "Start the module"))
        self.AddModule_Button.setText(_translate("Multi_Modules_Interface", "Add module"))
        self.pushButton_Info.setText(_translate("Multi_Modules_Interface", "Info"))
        self.label_8.setText(_translate("Multi_Modules_Interface", "Parametrs"))
        self.Clear_Button.setText(_translate("Multi_Modules_Interface", "Clear"))
        self.menuSave.setTitle(_translate("Multi_Modules_Interface", "File"))
        self.actionSave.setText(_translate("Multi_Modules_Interface", "Save"))
        self.actionReload.setText(_translate("Multi_Modules_Interface", "Reload"))
        self.actionCreate.setText(_translate("Multi_Modules_Interface", "Create"))
        self.actionLoad.setText(_translate("Multi_Modules_Interface", "Load"))
        self.actionClear_all.setText(_translate("Multi_Modules_Interface", "Clear all"))

